#!/usr/bin/env node
require = require('esm')(module/*, options*/)
require('dotenv').config()

const exitHook = require('async-exit-hook')
const { lockCheck, removeLock } = require('./src/system/lock')
const { run } = require('./src/cli/runner.js')

exitHook(async err => {
  await removeLock()
  process.exit(0)
})

async function waitForUnlock () {
  await lockCheck()

  try {
    await run()
  } catch (e) {}

  await removeLock()
}

waitForUnlock()
